import {
  Document,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  BorderStyle,
  AlignmentType,
} from 'docx';
import { AIResponse } from './aiAnalyzer';

/**
 * DOCX Document Generator
 * Generates professional SOC 2 compliance reports in .docx format
 */
export class DocxGenerator {
  /**
   * Generate a .docx document from AI analysis response
   * @param aiResponse - Validated AI analysis response
   * @param userEmail - User's email for footer
   * @param reportId - Report ID for footer
   * @returns Promise resolving to Buffer containing .docx file
   */
  async generateReport(
    aiResponse: AIResponse,
    userEmail: string,
    reportId: string
  ): Promise<Buffer> {
    const now = new Date();
    const formattedDate = now.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    // Build document sections
    const sections = [
      // Header
      new Paragraph({
        children: [
          new TextRun({
            text: 'Generated by ZCC AI',
            bold: true,
            size: 24,
          }),
        ],
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: `${formattedDate} | Requires Internal Sign-Off`,
            size: 20,
            italics: true,
          }),
        ],
      }),
      new Paragraph({ text: '' }), // Spacing

      // Title
      new Paragraph({
        children: [
          new TextRun({
            text: `SOC 2 Compliance Report: ${aiResponse.vendor_name}`,
            bold: true,
            size: 32,
          }),
        ],
      }),
      new Paragraph({ text: '' }), // Spacing

      // Vendor Overview Section
      new Paragraph({
        children: [
          new TextRun({
            text: 'Vendor Overview',
            bold: true,
            size: 28,
          }),
        ],
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: `Vendor Name: ${aiResponse.vendor_name}`,
          }),
        ],
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: `Report Type: ${aiResponse.report_type}`,
          }),
        ],
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: `Auditor Firm: ${aiResponse.auditor_firm}`,
          }),
        ],
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: `Audit Period: ${aiResponse.audit_period_start} to ${aiResponse.audit_period_end}`,
          }),
        ],
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: `Subservice Method: ${aiResponse.subservice_method}`,
          }),
        ],
      }),
      new Paragraph({ text: '' }), // Spacing

      // Trust Criteria
      new Paragraph({
        children: [
          new TextRun({
            text: 'Trust Criteria',
            bold: true,
            size: 24,
          }),
        ],
      }),
      ...aiResponse.trust_criteria.map(
        (criterion) =>
          new Paragraph({
            children: [
              new TextRun({
                text: criterion,
              }),
            ],
            bullet: {
              level: 0,
            },
          })
      ),
      new Paragraph({ text: '' }), // Spacing

      // Auditor's Opinion Section
      new Paragraph({
        children: [
          new TextRun({
            text: "Auditor's Opinion",
            bold: true,
            size: 28,
          }),
        ],
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: aiResponse.opinion,
            bold: true,
            size: 24,
            color: this.getOpinionColor(aiResponse.opinion),
          }),
        ],
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: aiResponse.opinion_summary,
          }),
        ],
      }),
      new Paragraph({ text: '' }), // Spacing

      // Subservice Organizations Section
      ...(aiResponse.subservice_organizations.length > 0
        ? [
            new Paragraph({
              children: [
                new TextRun({
                  text: 'Subservice Organizations',
                  bold: true,
                  size: 28,
                }),
              ],
            }),
            ...aiResponse.subservice_organizations.map(
              (org) =>
                new Paragraph({
                  children: [
                    new TextRun({
                      text: `${org.name}: ${org.services}`,
                    }),
                  ],
                  bullet: {
                    level: 0,
                  },
                })
            ),
            new Paragraph({ text: '' }), // Spacing
          ]
        : []),

      // Exceptions Table
      ...(aiResponse.exceptions.length > 0
        ? [
            new Paragraph({
              children: [
                new TextRun({
                  text: 'Exceptions',
                  bold: true,
                  size: 28,
                }),
              ],
            }),
            this.createExceptionsTable(aiResponse.exceptions),
            new Paragraph({ text: '' }), // Spacing
          ]
        : []),

      // CUECs Table
      ...(aiResponse.cuecs.length > 0
        ? [
            new Paragraph({
              children: [
                new TextRun({
                  text: 'CUEC Requirements',
                  bold: true,
                  size: 28,
                }),
              ],
            }),
            this.createCuecsTable(aiResponse.cuecs),
            new Paragraph({ text: '' }), // Spacing
          ]
        : []),

      // Reviewer Attestation
      new Paragraph({
        children: [
          new TextRun({
            text: 'Reviewer Attestation',
            bold: true,
            size: 28,
          }),
        ],
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: 'This report was generated by ZCC AI and requires internal sign-off from a qualified compliance reviewer. The reviewer must verify all findings, validate risk assessments, and confirm the accuracy of the analysis before this report is used for any compliance decisions.',
          }),
        ],
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: `Generated Report ID: ${reportId}`,
            size: 18,
            italics: true,
          }),
        ],
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: `Generated By: ${userEmail}`,
            size: 18,
            italics: true,
          }),
        ],
      }),
    ];

    const doc = new Document({
      sections: [
        {
          children: sections,
        },
      ],
    });

    const buffer = await Packer.toBuffer(doc);
    return buffer;
  }

  /**
   * Create exceptions table
   */
  private createExceptionsTable(
    exceptions: AIResponse['exceptions']
  ): Table {
    return new Table({
      width: {
        size: 100,
        type: 'percentage' as any,
      },
      rows: [
        // Header row
        new TableRow({
          height: {
            value: 400,
            rule: 'auto' as any,
          },
          children: [
            this.createHeaderCell('Category'),
            this.createHeaderCell('Description'),
            this.createHeaderCell('Vendor Response'),
            this.createHeaderCell('Risk Level'),
          ],
        }),
        // Data rows
        ...exceptions.map(
          (exception) =>
            new TableRow({
              children: [
                this.createDataCell(exception.category),
                this.createDataCell(exception.description),
                this.createDataCell(exception.vendor_response),
                this.createDataCell(
                  exception.ai_risk_level,
                  this.getRiskLevelColor(exception.ai_risk_level)
                ),
              ],
            })
        ),
      ],
    });
  }

  /**
   * Create CUECs table
   */
  private createCuecsTable(cuecs: AIResponse['cuecs']): Table {
    return new Table({
      width: {
        size: 100,
        type: 'percentage' as any,
      },
      rows: [
        // Header row
        new TableRow({
          height: {
            value: 400,
            rule: 'auto' as any,
          },
          children: [
            this.createHeaderCell('ID'),
            this.createHeaderCell('Requirement'),
          ],
        }),
        // Data rows
        ...cuecs.map(
          (cuec) =>
            new TableRow({
              children: [
                this.createDataCell(cuec.id),
                this.createDataCell(cuec.requirement),
              ],
            })
        ),
      ],
    });
  }

  /**
   * Create header cell for tables
   */
  private createHeaderCell(text: string): TableCell {
    return new TableCell({
      children: [
        new Paragraph({
          children: [
            new TextRun({
              text,
              bold: true,
              color: 'FFFFFF',
            }),
          ],
        }),
      ],
      shading: {
        fill: '366092',
        type: 'clear' as any,
      },
      borders: {
        top: {
          color: '000000',
          space: 1,
          style: BorderStyle.SINGLE,
          size: 6,
        },
        bottom: {
          color: '000000',
          space: 1,
          style: BorderStyle.SINGLE,
          size: 6,
        },
        left: {
          color: '000000',
          space: 1,
          style: BorderStyle.SINGLE,
          size: 6,
        },
        right: {
          color: '000000',
          space: 1,
          style: BorderStyle.SINGLE,
          size: 6,
        },
      },
    });
  }

  /**
   * Create data cell for tables
   */
  private createDataCell(text: string, color?: string): TableCell {
    return new TableCell({
      children: [
        new Paragraph({
          children: [
            new TextRun({
              text,
              color,
            }),
          ],
        }),
      ],
      borders: {
        top: {
          color: 'CCCCCC',
          space: 1,
          style: BorderStyle.SINGLE,
          size: 1,
        },
        bottom: {
          color: 'CCCCCC',
          space: 1,
          style: BorderStyle.SINGLE,
          size: 1,
        },
        left: {
          color: 'CCCCCC',
          space: 1,
          style: BorderStyle.SINGLE,
          size: 1,
        },
        right: {
          color: 'CCCCCC',
          space: 1,
          style: BorderStyle.SINGLE,
          size: 1,
        },
      },
    });
  }

  /**
   * Get color for opinion text
   */
  private getOpinionColor(opinion: string): string {
    switch (opinion) {
      case 'UNQUALIFIED':
        return '00B050'; // Green
      case 'QUALIFIED':
        return 'FFC000'; // Gold
      case 'ADVERSE':
        return 'C00000'; // Red
      case 'DISCLAIMER':
        return 'FF6B00'; // Orange
      default:
        return '000000'; // Black
    }
  }

  /**
   * Get color for risk level text
   */
  private getRiskLevelColor(riskLevel: string): string {
    switch (riskLevel) {
      case 'LOW':
        return '00B050'; // Green
      case 'MEDIUM':
        return 'FFC000'; // Gold
      case 'HIGH':
        return 'FF6B00'; // Orange
      case 'CRITICAL':
        return 'C00000'; // Red
      default:
        return '000000'; // Black
    }
  }
}

// Export singleton instance
export const docxGenerator = new DocxGenerator();
